"""Your migration message

Revision ID: 82f8ded36671
Revises: 07e996673de3
Create Date: 2025-03-26 23:48:06.455934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f8ded36671'
down_revision: Union[str, None] = '07e996673de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recognition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('result_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recognition_id'), 'recognition', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_id'), table_name='recognition')
    op.drop_table('recognition')
    # ### end Alembic commands ###
